spring:
  application:
    name: USER-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password: dileep@2021

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9090/eureka/



